apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
    description: zk
  creationTimestamp: "2020-01-28T09:00:41Z"
  generation: 9
  labels:
    k8s-app: zk
    qcloud-app: zk
  name: zk
  namespace: default
  resourceVersion: "8971375485"
  selfLink: /apis/apps/v1beta2/namespaces/default/deployments/zk
  uid: a95c551d-41ac-11ea-8203-068f3b461d43
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: zk
      qcloud-app: zk
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: zk
        qcloud-app: zk
        qcloud-redeploy-timestamp: "1585126567092"
    spec:
      containers:
      - env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: JAVA_HOME
          value: /usr/lib/jvm/java-7-openjdk-amd64
        - name: ZOOKEEPER_VERSION
          value: 3.4.14
        - name: ZK_HOME
          value: /opt/zookeeper-3.4.14
        image: ccr.ccs.tencentyun.com/flands/wurstmeister-zookeeper-docker:latest
        imagePullPolicy: Always
        name: zk
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 20m
            memory: 128Mi
        securityContext:
          privileged: false
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /etc/kafka/secrets
          name: secrets
        workingDir: /opt/zookeeper-3.4.14
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: qcloudregistrykey
      - name: tencenthubkey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /data/zk
          type: DirectoryOrCreate
        name: data
      - hostPath:
          path: /data/kafka/secrets
          type: DirectoryOrCreate
        name: secrets
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-03-25T08:56:50Z"
    lastUpdateTime: "2020-03-25T08:56:50Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-03-18T15:25:32Z"
    lastUpdateTime: "2020-03-25T08:56:50Z"
    message: ReplicaSet "zk-cc96fc766" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 9
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
