apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2020-03-07T07:52:43Z"
  generation: 4
  labels:
    k8s-app: consul
    app: traefik
  name: consul
  namespace: default
  selfLink: /apis/apps/v1beta2/namespaces/default/deployments/consul
  uid: a0b977c5-6048-11ea-8203-068f3b461d43
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: consul
      qcloud-app: consul
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: consul
        qcloud-app: consul
    spec:
      containers:
      - image: consul:latest
        imagePullPolicy: Always
        name: consul1
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 64Mi
        securityContext:
          privileged: false
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: qcloudregistrykey
      - name: tencenthubkey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-03-07T08:08:57Z"
    lastUpdateTime: "2020-03-07T08:08:57Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-03-07T07:52:43Z"
    lastUpdateTime: "2020-03-07T08:08:57Z"
    message: ReplicaSet "consul-86d888d64d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
