apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    description: gogs
  creationTimestamp: "2019-11-24T10:56:57Z"
  generation: 3
  labels:
    k8s-app: gogs
    qcloud-app: gogs
  name: gogs
  namespace: default
  resourceVersion: "8830406588"
  selfLink: /apis/apps/v1beta2/namespaces/default/deployments/gogs
  uid: 2247c201-0ea9-11ea-8dee-3a25aa8522bf
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: gogs
      qcloud-app: gogs
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: gogs
        qcloud-app: gogs
    spec:
      containers:
      - env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: GOGS_CUSTOM
          value: /data/gogs
        image: ccr.ccs.tencentyun.com/flands/gogs:1191
        imagePullPolicy: IfNotPresent
        name: gogs
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 256Mi
        securityContext:
          privileged: false
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
        workingDir: /app/gogs
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: qcloudregistrykey
      - name: tencenthubkey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /data/gogs
          type: DirectoryOrCreate
        name: data
